pipeline {
    agent any

    environment {
        // Оскільки ми встановили його в /usr/local/bin всередині контейнера
        TF_PATH = "terraform" 
    }

    stages {
        stage('Infrastructure Provisioning') {
            steps {
                script {
                    // Заходимо в папку, де лежить main.tf
                    dir('Lab_7') {
                        sh "terraform init"
                        sh "terraform apply -auto-approve"
                        // Генеруємо інвентар
                        sh "terraform output -raw ansible_inventory > inventory_auto.ini"
                    }
                }
            }
        }

        stage('Configuration & Deploy') {
            steps {
                script {
                    // Заходимо в папку, де лежить playbook.yml та новий inventory_auto.ini
                    dir('Lab_7') {
                        // Запускаємо Ansible
                        sh "ansible-playbook -i inventory_auto.ini playbook.yml"
                    }
                }
            }
        }
    }

    post {
        failure {
            echo "Щось пішло не так... Видаляємо ресурси."
            dir('Lab_7') {
                sh "terraform destroy -auto-approve"
            }
        }
        success {
            echo "Вітаю! Пайплайн відпрацював успішно."
        }
    }
}
