pipeline {
    agent any

    environment {
        // Шлях до Terraform, який ми ставили вручну
        TF_PATH = "/usr/local/bin/terraform"
    }

    stages {
        stage('Infrastructure Provisioning') {
            steps {
                script {
                    // Ініціалізація та запуск Terraform
                    sh "${TF_PATH} init"
                    sh "${TF_PATH} apply -auto-approve"
                    
                    // Генеруємо інвентар для Ansible
                    sh "${TF_PATH} output -raw ansible_inventory > inventory_auto.ini"
                }
            }
        }

        stage('Configuration & Deploy') {
            steps {
                script {
                    // Запуск Ansible (використовуємо той самий playbook, що в 6 лабі)
                    // Додаємо ігнорування ключів SSH на всякий випадок
                    sh "ansible-playbook -i inventory_auto.ini playbook.yml"
                }
            }
        }
    }

    post {
        failure {
            echo "Щось пішло не так... Видаляємо ресурси, щоб не смітити."
            sh "${TF_PATH} destroy -auto-approve"
        }
        success {
            echo "Успіх! Пайплайн завершено."
        }
    }
}
