---
- name: Configure All Nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Python 3
      raw: apt-get update && apt-get install -y python3
      changed_when: false

    - name: Install Nginx and Tools
      apt:
        name:
          - nginx
          - curl
          - net-tools
        state: present
        update_cache: yes

    - name: Start Nginx
      shell: service nginx start
      ignore_errors: yes
